services:
  client:
    build: ./vite-client
    ports: 
      - "5173:5173"
  server: 
    # wait for monogdb to start
    build: "./server"
    environment:
      - CONN_STR=mongodb://root:example@mongodb
    depends_on:
      - mongodb
    ports: 
      - "5173:5173"
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/foo
volumes:
  db-data: