services:
  client:
    build: ./client
    ports: 
      - "3000:3000"
  server: 
    build: "./server"
    environment:
      - CONN_STR=mongodb://root:example@mongodb
    depends_on:
      - mongodb
    ports: 
      - "3500:3500"

  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/foo
volumes:
  db-data: